(require 'spaceline-config)
(require 'diminish)

(display-time-mode -1)

(setq spaceline-buffer-size-p nil)
(setq spaceline-minor-modes-p t)
(setq spaceline-hud-p nil)
(setq spaceline-buffer-encoding-abbrev-p nil)
(setq spaceline-selection-info-p nil)
(setq spaceline-line-column-p nil)
(spaceline-emacs-theme)

(diminish 'global-whitespace-mode)
(diminish 'eproject-mode)
(diminish 'undo-tree-mode)
(diminish 'guru-mode)
(diminish 'subword-mode)
(diminish 'ivy-mode)
(diminish 'yas-minor-mode)
(diminish 'auto-complete-mode)
(diminish 'auto-highlight-symbol-mode)
(diminish 'abbrev-mode)
(diminish 'mml-mode)
(diminish 'ggtags-mode)
(diminish 'haskell-doc-mode)
(diminish 'hi2-mode)
(diminish 'hindent-mode)
(diminish 'with-editor-mode)

(diminish 'auto-revert-mode "AR")
(diminish 'overwrite-mode "O")
(diminish 'view-mode "V")
